### ISSUE TITLE
HTML file code block highlighting

### ISSUE THREAD

**Issue by djensen47** [bchiang7/halcyon-vscode#13]
I really like the code block highlighting in JavaScript, Golang, and other files but it seems to be missing from HTML files.

In case I'm using the wrong terminology, I'm referring to this ...
![image](https://user-images.githubusercontent.com/527865/59628981-ab314c00-90f6-11e9-82c7-90f867003a3b.png)

HTML files have a very subtle highlighting but I really like this bold color. Is there any way this can be added to the theme?

**Comment by bchiang7** [comment]
I think what you're referring to (the pink line) is from the [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extension

**Comment by djensen47** [comment]
Oh, sorry about that. This is very weird because I don't remember installing this and I didn't notice it until I installed Halcyon over the weekend. 😬
