### ISSUE TITLE
Green background for diffs on VS Code is too low contrast

### ISSUE THREAD

**Issue by djensen47** [bchiang7/halcyon-vscode#14]
I'm struggling with the selection of the green background color for code diffs on VS Code. The red backgound actually works great! The green however created a low contrast situation. When taken out of context like the following image, it doesn't look so bad but when it;s surrounded by the dark blue/indigo, it's rough on the eyes.

![image](https://user-images.githubusercontent.com/527865/59629374-838eb380-90f7-11e9-92a5-e01c31be8451.png)

**Comment by djensen47** [comment]
BTW, Halcyon is my new favorite theme. 😁

**Comment by bchiang7** [comment]
@djensen47 should be toned down in v0.2.2!
