### ISSUE TITLE
Menu is hard to see against sidebar

### ISSUE THREAD

**Issue by djensen47** [bchiang7/halcyon-vscode#15]
When I open a menu and it appears over the Explorer/Search/etc. sidebar, the colors match too closely and it's difficult to see where one end and the other begins.

I think Ayu Mirage Bordered has a very slight border on the menus. Maybe something like that will help.

![image](https://user-images.githubusercontent.com/527865/59643947-a1700e80-911f-11e9-9b19-0ebc89af0e00.png)

BTW, if this is the aesthetic that you prefer, then feel free to close this issue. Thanks again!

**Comment by bchiang7** [comment]
Thanks for all the great feedback! I don't have a windows machine to test on, but I darkened the widget shadows in v0.2.3, let me know if it helps!

**Comment by djensen47** [comment]
The new drop shadow looks great. Thanks!
