### ISSUE TITLE
Self closing tags in .vue files

### ISSUE THREAD

**Issue by Vorror** [bchiang7/halcyon-vscode#16]
There's a slight bug with self-closing tags in .vue files:
<img width="280" alt="Screen Shot 2019-08-18 at 4 28 08 PM" src="https://user-images.githubusercontent.com/3613230/63230033-6482cf80-c1d5-11e9-9a47-7052616350fa.png">

With Fix:
<img width="291" alt="Screen Shot 2019-08-18 at 4 26 58 PM" src="https://user-images.githubusercontent.com/3613230/63230047-9b58e580-c1d5-11e9-8605-8afe583ef60a.png">

Textmate override I'm using:

<img width="318" alt="Screen Shot 2019-08-18 at 4 30 39 PM" src="https://user-images.githubusercontent.com/3613230/63230046-9136e700-c1d5-11e9-8d60-e1486098a589.png">

**Comment by bchiang7** [comment]
Good suggestion! Addressed in #19
