### ISSUE TITLE
Fix golang imports

### ISSUE THREAD

**Issue by Vorror** [bchiang7/halcyon-vscode#17]
Current:

<img width="304" alt="Screen Shot 2019-08-18 at 4 38 16 PM" src="https://user-images.githubusercontent.com/3613230/63230145-d9a2d480-c1d6-11e9-86a9-66810c98b659.png">

Updated:

<img width="302" alt="Screen Shot 2019-08-18 at 4 38 29 PM" src="https://user-images.githubusercontent.com/3613230/63230154-e9bab400-c1d6-11e9-8c6d-f7a20ffa2240.png">

Fix I'm using:
```js
{
          "scope": "entity.name.import.go",
          "settings": {
            "foreground": "#bae67e",
          }
}
```

**Comment by bchiang7** [comment]
Good suggestion! Addressed in #19 and `v0.2.6`
