### ISSUE TITLE
"Disappeared" syntax in terminal

### ISSUE THREAD

**Issue by 01010101lzy** [bchiang7/halcyon-vscode#2]
Environment: Windows 10, VSCode 1.19.1.  
Halcyon version: 0.0.1

**Problem:** when typing `xxxx -x` (some program with parameter) in the terminal in VSCode, the `-x` syntax has the same color as the background, thus "disappears." See the attached picture.

![screenshot3](https://user-images.githubusercontent.com/10259119/34453546-9eb0c66c-ed92-11e7-9ea8-84d7303cd678.png)

**Comment by bchiang7** [comment]
Sorry, I don't use the terminal in VS Code, so I'm not sure what exactly would fix this. I also can't reproduce this problem, but I'm assuming it would either be this line https://github.com/bchiang7/halcyon-vscode/blob/master/themes/halcyon-color-theme.json#L227 or this line https://github.com/bchiang7/halcyon-vscode/blob/master/themes/halcyon-color-theme.json#L235.

If you edit those colors to be something other than `#212733` (the background color of the window) that should probably fix it. Let me know if you figure out and feel free to make a PR if you want

**Comment by 01010101lzy** [comment]
Thanks, that fixes it! The color I chose is a pretty random one (`#444a5e`), but it works great as expected.

![](https://ws1.sinaimg.cn/large/843e22d7ly1fmztb826moj208605kjrb.jpg)
