### ISSUE TITLE
Lower opacity of terminal selection

### ISSUE THREAD

**Issue by Vorror** [bchiang7/halcyon-vscode#20]
Currently, the selected text in the terminal field has an opaque color:

![image](https://user-images.githubusercontent.com/3613230/64366927-3d097080-cfe5-11e9-99ba-3edf04b3e75a.png)

I'm not sure what color we should use, but the property is called: ```terminal.selectionBackground```

**Comment by bchiang7** [comment]
Should be fixed in v0.2.9!
