### ISSUE TITLE
Reduce opacity for .gitignored files

### ISSUE THREAD

**Issue by Vorror** [bchiang7/halcyon-vscode#22]
Files/folders that are in `.gitignore` aren't reduced in opacity/saturation:

![image](https://user-images.githubusercontent.com/3613230/66221994-20bd2a00-e69e-11e9-9754-23d2421a5895.png)

In the above image, `dist` and `node_modules` should be grayed out.

**Comment by bchiang7** [comment]
Hello, so I do [support this](https://github.com/bchiang7/halcyon-vscode/blob/master/themes/halcyon-color-theme.json#L351) and it seems to be working for me, but I have found that sometimes VS Code doesn't properly grey out ignored resources. Reloading the editor usually fixes it 🤷‍♀ 

![image](https://user-images.githubusercontent.com/6599979/66223433-79da8d00-e6a1-11e9-9c43-1c1f5e70421f.png)

**Comment by Vorror** [comment]
@bchiang7 You're right! Thanks for the quick reply
