### ISSUE TITLE
Dark artifact recently showing on documents

### ISSUE THREAD

**Issue by ConduciveMammal** [bchiang7/halcyon-vscode#24]
Over the weekend, a dark artifact has begun showing on the document's background. This applies to new and existing documents and in split view.

![image](https://user-images.githubusercontent.com/18140157/69041916-3d13ec80-09e8-11ea-9d60-3925b73cc572.png)

**Comment by bchiang7** [comment]
Hi there, I can't seem to reproduce this...
- Have you tried reloading VS Code?
- Have you tested if this happens with other themes?
- Are you using a monitor?
- Which OS are you on?
