### ISSUE TITLE
Text illegible when hovering mouse over WSL icon on the bottom left corner

### ISSUE THREAD

**Issue by hichemfantar** [bchiang7/halcyon-vscode#34]
Before:
![image](https://user-images.githubusercontent.com/34947993/102926070-b0621a80-4494-11eb-92eb-1a9c95dcbfdd.png)
After:
![image](https://user-images.githubusercontent.com/34947993/102926089-b952ec00-4494-11eb-96d7-777f3c258e87.png)
You can kind of see the text in this example but only because it's highly zoomed in.

**Comment by bchiang7** [comment]
Thanks for pointing this out! Should be fixed in version `0.2.19`
