### ISSUE TITLE
Pixel alignment of file view next to editor with tabs

### ISSUE THREAD

**Issue by cdonohue** [bchiang7/halcyon-vscode#4]
Thank you for contributing this great theme! It has the perfect amount of contrast. Great work.

### Current Behavior
When the file explorer is the active side bar view, there is a `~2px` difference between the topmost list group and the editor with tabs
><img width="957" alt="screen shot 2018-01-03 at 8 51 36 am" src="https://user-images.githubusercontent.com/1928846/34525412-7ac2b6c8-f064-11e7-95df-3cb2d11d01dc.png">

### Possible Solution
Setting the `editorGroupHeader.tabsBorder` key to `#191E27` (the background of the side bar) seems to align the two areas
><img width="688" alt="screen shot 2018-01-03 at 9 04 48 am" src="https://user-images.githubusercontent.com/1928846/34525630-3942b9f4-f065-11e7-94dc-c99a4c9fc637.png">

**Comment by bchiang7** [comment]
Wow good eye! I'll include that fix in the next release :)
