### ISSUE TITLE
Inlay hints not enough contrast between background and text

### ISSUE THREAD

**Issue by hichemfantar** [bchiang7/halcyon-vscode#40]
The latest vscode version added inlay hints support (eg. parameter names now show when calling a function).
I've experimented and it seems that setting the text color to pure black and increasing the background alpha channel increases readability.
These are quick fixes through the dev tools CSS editor.
Before:
![image](https://user-images.githubusercontent.com/34947993/132258779-932e103a-7e6a-47fe-81cc-f1076186b6dd.png)
After setting text to black:
![image](https://user-images.githubusercontent.com/34947993/132258825-09a15b3a-36ea-4c14-9379-8d6af950e6cb.png)
After also increasing the background alpha from 0.6 to 1:
![image](https://user-images.githubusercontent.com/34947993/132258985-607f7be1-78c2-4cb8-8c61-050fab15d14d.png)

You can enable inlay hints through this setting:
![image](https://user-images.githubusercontent.com/34947993/132259907-df26ae7d-3f17-41f8-a1a7-a67fa4c980b0.png)

**Comment by bchiang7** [comment]
@hichemfantar Fixed this in release 0.2.22!
