### ISSUE TITLE
How to only use squiggly lines?

### ISSUE THREAD

**Issue by nealot** [bchiang7/halcyon-vscode#9]
Hey, love this theme! You've done a fantastic job with everything but one thing that continues to annoy me is how I can't seem to change the linting underline shape. With most themes, the underlines are squiggly and as such I have associated squiggly lines with linting errors. However, halcyon has a squiggly line underlined by two other lines which reduces my ability to recognize errors. I know this is a personal preference but I was wondering if you could tell me how to disable those lines and only keep the squiggly? I haven't been able to figure it out.

**Comment by bchiang7** [comment]
@nealot Thanks for bringing this to my attention! I've actually been thinking about disabling the underlines too, I think solely having the squiggly lines looks cleaner. I just released a new version 0.1.10

Just for your reference, the red underlines were `editorError.border` and `editorWarning.border`. Cheers!
